steps:
  - label: ":buildkite: :macos:"
    key: init
    command: |
      brew install orbstack
      which orbctl || echo "No orbctl found"
      which docker || echo "No docker found"
    agents:
      queue: mac
