agents:
  queue: "default"

image: "${BUILDKITE_HOSTED_REGISTRY_URL}/base:latest"

steps:
  - label: ":docker: image build"
    key: build
    if_changed:
      - ".buildkite/pipeline.yml"
      - ".buildkite/Dockerfile.build"
    image: ~
    command: |
      uname -a
      docker buildx build \
        --file .buildkite/Dockerfile.build \
        --build-arg BUILDKITE_BUILD_NUMBER="$$BUILDKITE_BUILD_NUMBER" \
        --platform linux/amd64 \
        --tag "${BUILDKITE_HOSTED_REGISTRY_URL}/base:latest" \
        --progress plain \
        --push .

  - label: ":pipeline: With tilde"
    depends_on: build
    key: run
    image: "${BUILDKITE_HOSTED_REGISTRY_URL}/base:latest"
    command: |
      echo "Running in the job now..."
      buildkite-agent --version
      uname -a
